# Generated by Django 5.1.1 on 2024-09-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NostroySmet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "date_of_inclusion_protocol",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("type_of_work", models.TextField(blank=True, null=True)),
                (
                    "date_of_exclusion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_worker",
                    models.CharField(
                        choices=[("ACTIVE", "Действует"), ("EXCLUDED", "Исключен")],
                        default="ACTIVE",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сметчик",
                "verbose_name_plural": "Сметчики",
            },
        ),
    ]
