# Generated by Django 5.1.1 on 2024-09-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nostroy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NostroyFiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number_img", models.URLField()),
                ("full_name_img", models.URLField()),
                (
                    "date_of_inclusion_protocol_img",
                    models.URLField(blank=True, null=True),
                ),
                ("date_of_modification_img", models.URLField(blank=True, null=True)),
                (
                    "date_of_issue_certificate_img",
                    models.URLField(blank=True, null=True),
                ),
                ("id_number", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "date_of_inclusion_protocol",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "date_of_modification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "date_of_issue_certificate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("type_of_work", models.TextField(blank=True, null=True)),
                (
                    "date_of_exclusion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status_worker",
                    models.CharField(
                        blank=True,
                        choices=[("ACTIVE", "Действует"), ("EXCLUDED", "Исключен")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("verified_id_number", models.BooleanField(default=False)),
                (
                    "id_number_verification_attempts",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("is_parsed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Физ-лицо",
                "verbose_name_plural": "Физ-лица",
                "unique_together": {("id_number_img", "full_name_img")},
            },
        ),
    ]
