# Generated by Django 5.1.1 on 2024-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nostroy", "0002_nostroyfiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nostroyfiz",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nostroyfiz",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
